### ISSUE TITLE
Tracking Issue for Module 6 FRAME

### ISSUE THREAD

**Issue by kianenigma** [Polkadot-Blockchain-Academy/pba-content#177]
# New Frame Lectures List

## Pre-requisite:

- [x] sp_runtime stuff: Depends on how mod 4 goes. 
- [x] `scale_codec` lecture @shawntabrizi 
- [x] `impl_trait_for_tuple` @kianenigma 
- [x] Crash course on PJS api

## FRAME Lectures

> Ordering constraint: things that I think should come before one another.

- error and call refund >> weight. Because of this, weight is explained broadly as a part of
  transactions (quite early), and then there is a separate lecture toward the end about the details
  and benchmarking.

### Essentials

- [x] Intro to FRAME #170 
  - simple-pallet
  - breeze over system, covers
    - Transient Storage Items
    - Some of the types
  - simple-runtime
  - executive
- [x] Dispatchable, Calls and Transactions @kianenigma  https://github.com/paritytech/polkadot-blockchain-academy/pull/219
  - Call Encoding (indices)
  - PostInfo and WeightRefund
  - Weight basics
- [x] Pallet Hooks + Inherent (@kianenigma )
- [x] Frame Storage (@shawntabrizi)
  - Transactional 
  - Partial collision resistance (from module 1)
- [ ] Origin (@shawntabrizi)
  - filtering
  - custom origins (system)
  - collective origin
  - example
- [x] Error and Events @shawntabrizi 
  - nested errors
  - sp_runtime DispatchError
  - Event Phases
- [ ] Testing a Pallet (@kianenigma)
  - How to write tests for a pallet.
  - ExtBuilder patter
  - `sp_io::TestExternalities`

---

### Slightly Less Important.

- [x] Outer Enum @shawntabrizi 
- [ ] Metadata @shawntabrizi 
- [ ] Benchmarking (@shawntabrizi) 
- [ ] Frame System: Revisiting and Leftover
  - PalletInfoAccess
  - Account Details: consumers, providers, sufficiency, etc
  - ChainContext, whatever the fuck it is.
- [ ] Frame Executive Revisiting and Leftover 

### Advance Topics
 
- [ ] Parity Patterns + Best-Practices
  - sanity-checks by Kian
  - Defensive traits Kian 
  - File/folder structure 
  - Pallets that receive/store calls + Dispatch
  - Key-less accounts, why/how they are safe.
  - 
  - ...
- [ ] Pallet Instancing
- [x] Signed Extensions, ValidateUnsigned TransactionValidity (priority) #154 
- [x] Migration + Try-Runtime #155 
- [ ] Custom RPCs + Runtime APIs (maybe, we will probably deprecate it)
- [ ] Digests

### Pallet Gallery

- [ ] Common Pallets: High level, no detail, as they might be subject to change.
  - Balances
  - Transaction Payment
  - Timestamp
  - Utility
  - MultiSig + Proxy
  - Babe + Aura + Grandpa

### Part Interesting Case Studies (for Q&A Sessions and such)
- [ ] Staking, Offchain Workers etc.
