### ISSUE TITLE
Slide style updates for BA 2023

### ISSUE THREAD

**Issue by nuke-web3** [Polkadot-Blockchain-Academy/pba-content#380]
Tracking issue to work with @Polkadot-Blockchain-Academy/design team on getting slides polished up!

[Internal figma]( https://www.figma.com/file/wctjWOVET50xiUt2rSsu5V/Polkadot-Blockchain-Academy-W2?node-id=0%3A1&t=bIfCAkBTeGnxA6Ck-1) - Let us know if you need access in this issue

- [x] https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/351
  - [x] #395
- [x] #167 
- [x] https://forum.parity.io/t/brand-stack-2-1-color-palette/1517 use brand colors and design
- [x] #401
- [x] Consider dark/light mode switch for slides
  - [x] toggle on slides via top right logo (or keyboard shortcut?) 
  - [x] select code highlight to match https://github.com/highlightjs/highlight.js/tree/main/src/styles
- [x] #591
- [x]  ...more?
