### ISSUE TITLE
Shawn Tracking Issue

### ISSUE THREAD

**Issue by shawntabrizi** [Polkadot-Blockchain-Academy/pba-content#441]
Here are a list of tasks I hope to tackle by the end of this academy.

- [x] Check that there is some inclusion and setup of Blockspace between the Blockchain and Polkadot modules.
    - https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/430
- [x] Review and update the FRAME section.
    - [x] Add a 5 Day Agenda https://github.com/Polkadot-Blockchain-Academy/pba-content/pull/451
    - [x] Add Benchmarking lecture. https://github.com/Polkadot-Blockchain-Academy/pba-content/pull/461
        - [x] Extra lecture https://github.com/Polkadot-Blockchain-Academy/pba-content/pull/484
    - [x] Benchmarking exercise https://github.com/Polkadot-Blockchain-Academy/pba-content/pull/453
    - [x] Add more details around Transactional storage.
    - [x] Remove references to "verify first, write last"
    - [x] Update exercises
        - [x] Make them slightly more concise
        - [ ] See if I can better connect them to XCM and Connecting to Relay Chain exercises.
- [ ] Review Other Modules
    - [x] Substrate
    - [x] FRAME
    - [ ] Polkadot
    - [ ] XCM
- [ ] (maybe?) work on kitties tutorial
