### ISSUE TITLE
Shawn Tabrizi - Tracking Issue - Berkeley

### ISSUE THREAD

**Issue by shawntabrizi** [Polkadot-Blockchain-Academy/pba-content#592]
Hey all,

This will be a tracking issue, and a great way to contact me for my work and participation in the upcoming PBA in Berkeley, California.

I will try to push most conversations, work items, and commitments into this GitHub issue to make it easy to track for myself and others.

I currently have 30 days contracted to me for my work at the academy, which I will need to split over my time in person at the academy and any work before.

I am happy to spend all of that time at the academy in person, but it seems like some work is needed beforehand.

cc @NukeManDan @aaronbassett @kianenigma 

---

Current Open Questions:

- What lessons will I be teaching / TA-ing?
    - Likely any combination of Substrate, FRAME, and perhaps some of Polkadot (introduction, high level, economics / game theory, ending overview) will match well my abilities.
    - This will help me decide how many days I need to allocate for being there in person (at least).
- What content needs my help?
    - Here are some things I can think of wanting to work on if I could and it makes sense:
        - An update to the Polkadot introduction / ending lecture. Trying to primarily paint a high level picture of how everything learned so far applies to Polkadot.
        - A simplification / break down / expansion of the FRAME exam.
            - Something that is easier to grade, and has less variance across the options.
            - Something which avoids people copying the DEX project. (perhaps as simple as forcing Uniswap V2)
            - Perhaps better starting templates.
            - Perhaps breaking down the overall project over two weekends.
            - Integration of things like Polkadot and XCM content into a final project.
        - Improvements to visuals / diagrams across all sections.
        - Video lecture that people can watch / take home to facilitate the in-class learning.
- What other ways would you all like to use my time?

---

Current Responsibilities:

- [ ] Re-organize the Polkadot Module: https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/605
    - [ ] Review and Revise Introduction to Polkadot
    - [ ] Polkadot Ecosystem / Economy Slides
    - [ ] Cross Chain Message Passing
    - [ ] Blockchain Decisions and Scalability
- [ ] Help create FRAME multi-stage tutorial w/ @kianenigma
