### ISSUE TITLE
PBA3 Berkeley - Cryptography Tracking Issue

### ISSUE THREAD

**Issue by naterarmstrong** [Polkadot-Blockchain-Academy/pba-content#604]
# PBA3 - Cryptography Tracking Issue

## Overall Module Logistics
Staff:
- Nate (@naterarmstrong) - lead SME
	- On site the whole first week + following weekend
	- Lives in Berkeley, so no need to worry about accomodation dates
- Nuke  (@NukeManDan) - TA
	- On site the whole academy regardless
- Maciej Żyszkiewicz (@Overkillus) - Content development support
	- Remote content development support
	- For now, no in-person aspect

Delivery Dates:
- Possibly some on July 10: Still TBD based on schedule, econ half, potential new content
- July 11-12th: Lecture / many time pad exercise
- July 14/15: Assignment release, office hours + assignment support

Primary Ownership:
- Delivery: Nate
- Grading: Nate
- Office hours: Nate
- Assignment 1: Nate
- Many-time pad activity: Nuke

### Lectures
- Lecture review
	- [x] Introduction
	- [x] Hashes
	- [x] Encryption
	- [x] Digital Signatures Basic
	- [x] Digital Signatures Advanced
	- [x] Hash Based Data Structures
	- [x] Exotic Primitives
		- [x] More deeply integrate erasure encodings into exercises (As mentioned by @JoshOrndorff)
- Cryptography in context lecture development
	- [Draft PR](https://github.com/Polkadot-Blockchain-Academy/pba-content/pull/608)
	- Goals to get across:
		- DO NOT ROLL YOUR OWN CRYPTO
		- what does it mean for something to be "secret" in context of cryptographic primitives
			- side channel attacks are possible if not very careful in coding
			- compromised digital/physical security can also lead to key loss (very roughly touch on this, more in academic context than anything else)
		- security inversely related to availability, in general
	- Goal length:
		- <45 min

### Assignment / Exercises
- Assignment
	- hash based data structure section
		- Basic Merkle tree
			- [x] Skeleton code / instructions / sanity check tests
			- [x] Solution
			- [x] Full test suite
		- Merkle multiproofs
			- [x] Skeleton code / instructions / sanity check tests ([branch](https://github.com/Polkadot-Blockchain-Academy/pba-ctf-assignment--master/tree/nate-merkle-no-solution))
			- [x] Solution ([branch](https://github.com/Polkadot-Blockchain-Academy/pba-ctf-assignment--master/tree/nate-merkle))
			- [x] Full test suite
		- DID NOT DO: (Maybe) Tries
		- Proof space comparisons
			- [x] Skeleton code / instructions / sanity check tests
			- [x] Solution
			- [x] Full test suite
	- Cryptographic potpourri section (formerly CTF)
		- Pull request in ctf repository: [here](https://github.com/Polkadot-Blockchain-Academy/pba-ctf-assignment--master/pull/20)
		- [x] Complete
	- Overall design of this side, and what parts should be an exercise vs assignment is all still TBD. There's not much useful material from the previous CTF.
	- [x] Collaborate with Econ to make a coherent + appropriately difficult assignment
- Exercise 1 (many time pad)
	- [x] Polish @NukeManDan 
- Exercise 2 (formerly VRF poker)
	- [X] Did not do: Redesign and fill in specific details, or link an exercise 2 issue
