### ISSUE TITLE
PBA3 Berkeley - Polkadot Tracking Issue

### ISSUE THREAD

**Issue by shawntabrizi** [Polkadot-Blockchain-Academy/pba-content#605]
cc @BradleyOlson64 @Sophia-Gold @JoshOrndorff 

Related and needs feedback integrated:

- [ ] https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/564
- [ ] https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/552

TODO:

- [x] Create new lesson plan layout
- [x] Distribute content creation
- [x] Distribute presentations
- [ ] Revise Exercise
