### ISSUE TITLE
Tracking Issue Substrate Module PBA3 

### ISSUE THREAD

**Issue by kianenigma** [Polkadot-Blockchain-Academy/pba-content#620]
- [x] Better diagrams, perhaps use mermaid 
  - https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/437#issuecomment-1387507513
  - https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/380#issuecomment-1573426650
- [ ] revive tx-pool, find a spot for it. @JoshOrndorff 
- [ ] based on the progress made in efforts like the polkadot-sdk mono-repo, https://github.com/paritytech/substrate/pull/14137 and such, I might revise and shrink "substrate-folder-structure".
- [x] General addressing of my post-lecture slides. 
- [x] I want to revise the Merklized storage lecture, and frame it more around the concept of PoV. @JoshOrndorff would need to sync with you a bit, to see if/how Merkle proofs are covered in mod3. 
- [x] revive frame-less template, and make it ready for auto-grading https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/662, and aligned with `mini_substrate`
  - [ ] add proper nonce as a requirement to the assignment. 

Other misc. tasks:

- [x] `substrate` crate docs, explaining some high level things and folder structure.  https://github.com/paritytech/substrate/pull/14581
- [x] improve docs for `sp_io` https://github.com/paritytech/substrate/pull/14581
- [x] improve docs for `sp_runtime::traits` https://github.com/paritytech/substrate/pull/14583
- [ ] `sp-keyring`
- [ ] improve example/docs for `ProofRecorder` etc. An example of generating proof, even deletion proof would be good.

Other relevant substrate PRs

- https://github.com/paritytech/substrate/pull/14581
- https://github.com/paritytech/substrate/pull/14583
- https://github.com/paritytech/substrate/pull/14578
- https://github.com/paritytech/substrate/pull/14137
- https://github.com/paritytech/substrate/pull/13987
