### ISSUE TITLE
PBA@UCB Mod1 - Cryptorgraphy Content Dry Runs & Beta Testing

### ISSUE THREAD

**Issue by nuke-web3** [Polkadot-Blockchain-Academy/pba-content#621]
Context: https://github.com/Polkadot-Blockchain-Academy/pba-content/discussions/603#discussion-5165792

This issue servers to concretely define the lessons and associated content that will need testing before we deliver it for the Berkeley cohort (July 10th, 2023) . cc @naterarmstrong @NukeManDan 

Related to #604

## Dry runs

- [x] Cryptography in context

## Beta Testing

- [ ] Extended Merkle Tree Assignment (Review by EOD July 8)
- [ ] Cryptography Grabbag Exercises/Assignment (Review by EOD July 8)
