### ISSUE TITLE
PBA@UCB Mod7 - Polkadot Content Dry Runs & Beta Testing

### ISSUE THREAD

**Issue by nuke-web3** [Polkadot-Blockchain-Academy/pba-content#629]
Context: https://github.com/Polkadot-Blockchain-Academy/pba-content/discussions/603#discussion-5165792

This issue servers to concretely define the lessons and associated content that will need testing before we deliver it for the Berkeley cohort (July 10th, 2023) . cc @BradleyOlson64 @Sophia-Gold @shawntabrizi @JoshOrndorff

Related: #605

## Dry runs

- [ ] <list out lessons and (tentative/proposed) dates they will run>
- [ ] https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/605#issuecomment-1573953786

## Beta Testing

- [ ] <list hands-on exercises/activities and assignments that need to be reviewed/tested with a deadline to provide solutions and feedback>
