### ISSUE TITLE
PREP TO GO PUBLIC 🎉 - Polish slides from feeedback and local tweaks made durring run-of-show at Berkelely

### ISSUE THREAD

**Issue by NukeManDan** [Polkadot-Blockchain-Academy/pba-content#708]
Dear @Polkadot-Blockchain-Academy/faculty ,

:rocket:  As part of our commitment to knowledge sharing, drive innovation in the web3 space and foster a more inclusive blockchain ecosystem, we are **opening the content of the Academy**. This is a decision endorsed by Gav earlier in the year and we are excited to make this content available too everyone!

In preparation for this, we will ask you to take some time to polish the content here and get it as best it can be for the world stage :stadium: 

#### _Our goal: review and get all open PRs merged no latter than the 21st._

---

Inevitably you are going to find things in the UCB run-of-show and make local changes to slides - that is totally fine!
We also have fresh ideas and feedback to act on.

We track those per module in this issue:
 
- [x] #709
- [ ] #710
- [ ] #735
- [ ] #761
- [ ] #790
- [ ] #791
- [ ] #792

### More TODO Items

- [ ] @NukeManDan  to tag all repos for cohot (slides, code, etc.)
- [ ] Structure of various repos we use to be more uniform and well documented (pr @kianenigma  request)
- [ ] All file names, first slide with `<h1>` tag, and md yaml headers _must_ match
- [ ] https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/796
- [x] #839 
- [ ] Update CONTRIBUTING doc with updated conventions:
  - ```
    syllabus
    ├── X-Module
    │  ├── img
    │  │  ├── something.svg
    │  │  ├── raster.png
    │  │  └── ...
    │  ├── Y-Lesson_Title-slides.md
    │  ├── ...
     ...
    ```

### Notes

- Strategy and comments on how to gather student feedback: https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/734

**Comment by wirednkod** [comment]
This is public now, so it can close
