### ISSUE TITLE
Cryptography - Feedback and local tweaks from UCB run-of-show incoperated

### ISSUE THREAD

**Issue by NukeManDan** [Polkadot-Blockchain-Academy/pba-content#709]
- [ ] update https://github.com/Polkadot-Blockchain-Academy/pba-cryptography--master as well from student feeback and https://gist.github.com/naterarmstrong/a04cd8604dc4604ba852b6a329cddb77
- [ ] update the mod README with the schedule that actually happened for reference.

### TODO before UCB tag is applied

- [ ] https://github.com/Polkadot-Blockchain-Academy/pba-cryptography--master/issues/2
- [ ] Review https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/604 for things we missed
