### ISSUE TITLE
[Meta] Student feedback intake  improvements

### ISSUE THREAD

**Issue by nuke-web3** [Polkadot-Blockchain-Academy/pba-content#721]
https://github.com/Polkadot-Blockchain-Academy/pba-ucb-2023/discussions was an attempt to gather feedback, so far in week 1 at UCB has zero activity.... if this does end up being useful as a tool, we can improve the UX by:

- [ ] Document how to setup cryptpad for truly anonymous to PBA forms students can use.
- [ ] Using the proper template format https://docs.github.com/en/discussions/quickstart
- [ ] Using the Repo for something much closer to the code (static slides) that is intended to be implemented
   -  This could be the base that CI uses to publish a _public_ cohort-specific set of slides (maybe a branch per cohort in this private repo instead) 
   - Perhaps this becomes a monorepo of private materials that are not generated by gh classroom _per student_, thus all shared private materials.
