### ISSUE TITLE
Substrate - Feedback and local tweaks from UCB run-of-show incoperated

### ISSUE THREAD

**Issue by nuke-web3** [Polkadot-Blockchain-Academy/pba-content#761]
### TODO before we close out the UCB cohort & tag the content repo

- [ ] Remove substrate module slides to remove what we didn't cover (or mention) on notion. 
- [x] https://github.com/Polkadot-Blockchain-Academy/frameless-node-template--master/issues/3
- [x] Tips and Tricks lecture: 
  - [x] `XXXNoBound` stuff. 
  - [x] Read your errors top to bottom!
