### ISSUE TITLE
PBA@UCB: Graded Assignments and Certification Outcomes

### ISSUE THREAD

**Issue by nuke-web3** [Polkadot-Blockchain-Academy/pba-content#798]
> WIP comment here, edited over time!

### Assignment 1 - [here](https://github.com/Polkadot-Blockchain-Academy/pba-ucb-a1--crypto)

  - [x] Grades completed - [here](https://github.com/Polkadot-Blockchain-Academy/ucb-cryptography-grading)
  - [x] Grades sent - [example](https://github.com/Polkadot-Blockchain-Academy/ucb-cryptography-grading/issues/3)
  - [x] Feedback gathered - [here](https://cryptpad.fr/form/#/3/form/view/03640ab93fc44d203d4616d21b8d5c2a/auditor=a3k5ZTNzaENJVVdXNXRkWEVTUFhjTS9mYVNlYVRmMmc=/)
  - [x] Post-mortem analysis completed - [here](https://github.com/Polkadot-Blockchain-Academy/pba-cryptography--master/issues/4)

### Assignment 2 - [here](https://github.com/Polkadot-Blockchain-Academy/pba-ucb-a2-contracts) 

  - [ ] Grades completed
  - [ ] Grades sent 
  - [x] Feedback gathered - [here](https://cryptpad.fr/form/#/1/view/KWhtmon0F-5-ZqPqfXSHIg/+z5D-7fdnT7oYmsVn+cy5HTOCXIwjLv+SazX-S3E2GA=/auditor=VEo3MHB5M0k5dXIvZ0FXMkYzOFJ1dFE2cUkxQkY5Sm4=/)
  - [ ] Post-mortem analysis completed

### Assignment 3 - [here](https://github.com/Polkadot-Blockchain-Academy/pba-ucb-frameles-node-template)

  - [ ] Grades completed
  - [ ] Grades sent 
  - [ ] Feedback gathered - [here](https://cryptpad.fr/form/#/1/view/UEvGm6iZ34JPxVmHszynNw/Fs8C0EfwgjmsDV4GGPCBcYaMGdO8O7YpI2rc6A0+3Gc=/auditor=WXRWVVU1cDRzS29wMTQ5VFFYbG5hcEoyRXdTVXhPSkY=/)
  - [ ] Post-mortem analysis completed

### Assignment 4 - [master](https://github.com/Polkadot-Blockchain-Academy/frame-assignment--master)

  - [ ] Grades completed
  - [ ] Grades sent 
  - [ ] Feedback gathered
  - [ ] Post-mortem analysis completed

## Certifications

- [ ] Weights per assignment decided (if any)
- [ ] Weights communicated to students w. rational
- [ ] Certification criteria final
- [ ] Certification decisions final
- [ ] Certification communicated
- [ ] NFTs delivered (where applicable)
- [ ] Post-mortem analysis completed
